import { join } from 'node:path';
import { Module } from '@nestjs/common';
import { WorkflowModule } from 'workflow/nest';
import { AppController } from './app.controller.js';

// Force-enable manifest serving on Vercel
if (process.env.VERCEL) {
  process.env.WORKFLOW_PUBLIC_MANIFEST = '1';
}

// Import the manifest generated by workflow-nest build (runs in prebuild).
// This is a standard ESM import that SWC compiles and NFT traces.
let manifestJson: string | undefined;
try {
  const { manifestJson: data } = await import('./_manifest-data.js');
  manifestJson = data;
} catch {
  // File doesn't exist during first dev build
}

@Module({
  imports: [
    WorkflowModule.forRoot({
      skipBuild: !!process.env.VERCEL,
      // On Vercel, the bundle files are copied to dist/workflow/ by nest-cli
      // assets. Point outDir there so the controller can import them.
      ...(process.env.VERCEL
        ? { outDir: join(process.cwd(), 'dist', 'workflow') }
        : {}),
      ...(manifestJson ? { manifestJson } : {}),
    }),
  ],
  controllers: [AppController],
})
export class AppModule {}
