packages:
  - workbench/*
  - "!workbench/nitro"
  - packages/*
  - docs

catalog:
  "@biomejs/biome": ^2.4.4
  "@swc/core": 1.15.3
  "@types/json-schema": ^7.0.15
  "@types/node": 22.19.0
  "@vercel/functions": ^3.4.3
  "@vercel/oidc": 3.2.0
  "@vercel/queue": 0.1.4
  "@vitest/coverage-v8": ^4.0.18
  ai: 6.0.116
  esbuild: ^0.27.3
  nitro: 3.0.1-alpha.1
  semver: 7.7.4
  typescript: ^5.9.3
  ulid: ~3.0.1
  undici: 7.22.0
  vitest: ^4.0.18
  zod: 4.3.6

onlyBuiltDependencies:
  - esbuild

savePrefix: ""
