/**
 * Shared utilities for detecting files that need workflow transformation.
 * Used by builders, rollup plugin, Next.js loader, and vite plugin.
 */

// Matches: 'use workflow'; "use workflow"; 'use step'; "use step"; at line start with optional whitespace
export const useWorkflowPattern = /^\s*(['"])use workflow\1;?\s*$/m;
export const useStepPattern = /^\s*(['"])use step\1;?\s*$/m;

// Matches imports from '@workflow/serde' (for custom class serialization)
// e.g.: import { WORKFLOW_SERIALIZE } from '@workflow/serde';
export const workflowSerdeImportPattern = /from\s+(['"])@workflow\/serde\1/;

// Matches direct usage of Symbol.for('workflow-serialize') or Symbol.for('workflow-deserialize')
// e.g.: static [Symbol.for('workflow-serialize')](instance) { ... }
export const workflowSerdeSymbolPattern =
  /Symbol\.for\s*\(\s*(['"])workflow-(?:serialize|deserialize)\1\s*\)/;

// Pattern to detect generated workflow route files that should be excluded
// These files are generated by the build process and should not be re-processed
export const generatedWorkflowPathPattern =
  /[/\\]\.well-known[/\\]workflow[/\\]/;

// Pattern to detect @workflow SDK packages that should be excluded from transformation
// These are internal SDK packages that should not be treated as user entry points.
// Matches both: node_modules/@workflow/* and monorepo packages/*/dist paths
// User npm packages with workflows/steps/serde SHOULD still be discovered.
export const workflowSdkPathPattern =
  /[/\\](?:node_modules[/\\]@workflow[/\\]|packages[/\\](?:builders|core|rollup|vite|next|nitro|serde|workflow|swc-plugin-workflow)[/\\])/;

/**
 * Detects workflow-related patterns in source code.
 */
export interface WorkflowPatternMatch {
  /** File contains 'use workflow' directive */
  hasUseWorkflow: boolean;
  /** File contains 'use step' directive */
  hasUseStep: boolean;
  /** File contains @workflow/serde import */
  hasSerdeImport: boolean;
  /** File contains Symbol.for('workflow-serialize') or Symbol.for('workflow-deserialize') */
  hasSerdeSymbol: boolean;
  /** File contains any directive ('use workflow' or 'use step') */
  hasDirective: boolean;
  /** File contains any serde pattern (import or Symbol.for) */
  hasSerde: boolean;
}

/**
 * Detects workflow-related patterns in source code.
 * @param source - The source code to analyze
 * @returns Object with flags for each detected pattern
 */
export function detectWorkflowPatterns(source: string): WorkflowPatternMatch {
  const hasUseWorkflow = useWorkflowPattern.test(source);
  const hasUseStep = useStepPattern.test(source);
  const hasSerdeImport = workflowSerdeImportPattern.test(source);
  const hasSerdeSymbol = workflowSerdeSymbolPattern.test(source);

  return {
    hasUseWorkflow,
    hasUseStep,
    hasSerdeImport,
    hasSerdeSymbol,
    hasDirective: hasUseWorkflow || hasUseStep,
    hasSerde: hasSerdeImport || hasSerdeSymbol,
  };
}

/**
 * Determines if a file path is a generated workflow route file.
 * @param filePath - The file path to check
 * @returns true if the file is a generated workflow route
 */
export function isGeneratedWorkflowFile(filePath: string): boolean {
  return generatedWorkflowPathPattern.test(filePath);
}

/**
 * Determines if a file path is part of the @workflow SDK.
 * @param filePath - The file path to check
 * @returns true if the file is part of the @workflow SDK
 */
export function isWorkflowSdkFile(filePath: string): boolean {
  return workflowSdkPathPattern.test(filePath);
}

/**
 * Determines if a file should be transformed based on its path and content patterns.
 *
 * Logic:
 * - Generated workflow route files are never transformed
 * - Files with directives ('use workflow' or 'use step') are always transformed
 * - Files with serde patterns are transformed, unless they're @workflow SDK files
 *   (SDK files with serde patterns are internal implementation, not user code)
 *
 * @param filePath - The file path to check
 * @param patterns - The detected patterns from detectWorkflowPatterns()
 * @returns true if the file should be transformed
 */
export function shouldTransformFile(
  filePath: string,
  patterns: WorkflowPatternMatch
): boolean {
  // Never transform generated workflow route files
  if (isGeneratedWorkflowFile(filePath)) {
    return false;
  }

  // Always transform files with directives
  if (patterns.hasDirective) {
    return true;
  }

  // Transform files with serde patterns, unless they're @workflow SDK files
  if (patterns.hasSerde) {
    return !isWorkflowSdkFile(filePath);
  }

  return false;
}

/**
 * Combined regex pattern for turbopack content matching.
 * Uses backreferences to ensure matching quote types.
 * Matches: 'use workflow', 'use step', @workflow/serde imports, and Symbol.for serialization symbols
 */
export const turbopackContentPattern =
  /(use workflow|use step|from\s+(['"])@workflow\/serde\2|Symbol\.for\s*\(\s*(['"])workflow-(?:serialize|deserialize)\3\s*\))/;
