/**
 * Shared utilities for detecting files that need workflow transformation.
 * Used by builders, rollup plugin, Next.js loader, and vite plugin.
 */

// Matches: 'use workflow'; "use workflow"; 'use step'; "use step"; at line start with optional whitespace
export const useWorkflowPattern = /^\s*(['"])use workflow\1;?\s*$/m;
export const useStepPattern = /^\s*(['"])use step\1;?\s*$/m;

// Matches imports from '@workflow/serde' (for custom class serialization)
// e.g.: import { WORKFLOW_SERIALIZE } from '@workflow/serde';
export const workflowSerdeImportPattern = /from\s+(['"])@workflow\/serde\1/;

// Matches direct usage of Symbol.for('workflow-serialize') or Symbol.for('workflow-deserialize')
// e.g.: static [Symbol.for('workflow-serialize')](instance) { ... }
export const workflowSerdeSymbolPattern =
  /Symbol\.for\s*\(\s*(['"])workflow-(?:serialize|deserialize)\1\s*\)/;

// Matches usage of WORKFLOW_SERIALIZE or WORKFLOW_DESERIALIZE as computed property names
// e.g.: static [WORKFLOW_SERIALIZE](instance) { ... }
// This catches cases where the symbols are imported and used (even if bundled/re-exported)
export const workflowSerdeComputedPropertyPattern =
  /\[\s*WORKFLOW_(?:SERIALIZE|DESERIALIZE)\s*\]/;

// Pattern to detect generated workflow route files that should be excluded
// These files are generated by the build process and should not be re-processed
export const generatedWorkflowPathPattern =
  /[/\\]\.well-known[/\\]workflow[/\\]/;

/**
 * Checks whether a file path belongs to serde infrastructure code that should
 * be excluded from serde discovery and transformation. These files match serde
 * patterns (e.g. they import `@workflow/serde` or reference the symbols) but do
 * NOT define any classes that implement the serde protocol.
 *
 * Excluded files:
 * - `@workflow/serde` package: only defines the `WORKFLOW_SERIALIZE` /
 *   `WORKFLOW_DESERIALIZE` symbol constants.
 * - `@workflow/core` serialization module (`serialization.{ts,js}`): the
 *   runtime serialization engine that uses the symbols for introspection.
 *
 * Other files within `@workflow/*` packages (including those that define
 * serde-implementing classes) are intentionally NOT excluded.
 */
export function isSerdeInfrastructureFile(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, '/');

  // The @workflow/serde package only exports the WORKFLOW_SERIALIZE and
  // WORKFLOW_DESERIALIZE symbol constants. It will never contain classes.
  // Handles both standard and pnpm virtual store paths, e.g.:
  //   node_modules/@workflow/serde/dist/index.js
  //   node_modules/.pnpm/@workflow+serde@1.0.0/node_modules/@workflow/serde/dist/index.js
  //   packages/serde/src/index.ts  (monorepo)
  if (
    normalized.includes('/node_modules/@workflow/serde/') ||
    normalized.includes('/packages/serde/')
  ) {
    return true;
  }

  // The serialization module in @workflow/core is the runtime serialization
  // engine. It imports and uses the serde symbols for runtime introspection
  // but does not define any classes that implement the serde protocol.
  // We check that the file is inside @workflow/core AND the basename is
  // "serialization.*" (e.g. serialization.ts, serialization.js).
  const isInCore =
    normalized.includes('/node_modules/@workflow/core/') ||
    normalized.includes('/packages/core/');
  if (isInCore) {
    const lastSlash = normalized.lastIndexOf('/');
    const basename =
      lastSlash >= 0 ? normalized.slice(lastSlash + 1) : normalized;
    if (basename.startsWith('serialization.')) {
      return true;
    }
  }

  return false;
}

/**
 * Detects workflow-related patterns in source code.
 */
export interface WorkflowPatternMatch {
  /** File contains 'use workflow' directive */
  hasUseWorkflow: boolean;
  /** File contains 'use step' directive */
  hasUseStep: boolean;
  /** File contains @workflow/serde import */
  hasSerdeImport: boolean;
  /** File contains Symbol.for('workflow-serialize') or Symbol.for('workflow-deserialize') */
  hasSerdeSymbol: boolean;
  /** File contains any directive ('use workflow' or 'use step') */
  hasDirective: boolean;
  /** File contains any serde pattern (import or Symbol.for) */
  hasSerde: boolean;
}

/**
 * Detects workflow-related patterns in source code.
 * @param source - The source code to analyze
 * @returns Object with flags for each detected pattern
 */
export function detectWorkflowPatterns(source: string): WorkflowPatternMatch {
  const hasUseWorkflow = useWorkflowPattern.test(source);
  const hasUseStep = useStepPattern.test(source);
  const hasSerdeImport = workflowSerdeImportPattern.test(source);
  const hasSerdeSymbol = workflowSerdeSymbolPattern.test(source);
  const hasSerdeComputedProperty =
    workflowSerdeComputedPropertyPattern.test(source);

  return {
    hasUseWorkflow,
    hasUseStep,
    hasSerdeImport,
    hasSerdeSymbol,
    hasDirective: hasUseWorkflow || hasUseStep,
    hasSerde: hasSerdeImport || hasSerdeSymbol || hasSerdeComputedProperty,
  };
}

/**
 * Determines if a file path is a generated workflow route file.
 * @param filePath - The file path to check
 * @returns true if the file is a generated workflow route
 */
export function isGeneratedWorkflowFile(filePath: string): boolean {
  return generatedWorkflowPathPattern.test(filePath);
}

/**
 * Determines if a file should be transformed based on its path and content patterns.
 *
 * Logic:
 * - Generated workflow route files are never transformed
 * - Files with directives ('use workflow' or 'use step') are always transformed
 * - Files with serde patterns are transformed, unless they're serde infrastructure
 *   files (e.g. @workflow/serde constants, @workflow/core serialization engine)
 *
 * @param filePath - The file path to check
 * @param patterns - The detected patterns from detectWorkflowPatterns()
 * @returns true if the file should be transformed
 */
export function shouldTransformFile(
  filePath: string,
  patterns: WorkflowPatternMatch
): boolean {
  // Never transform generated workflow route files
  if (isGeneratedWorkflowFile(filePath)) {
    return false;
  }

  // Always transform files with directives
  if (patterns.hasDirective) {
    return true;
  }

  // Transform files with serde patterns, unless they're serde infrastructure files
  if (patterns.hasSerde) {
    return !isSerdeInfrastructureFile(filePath);
  }

  return false;
}

/**
 * Combined regex pattern for turbopack content matching.
 * Uses backreferences to ensure matching quote types.
 * Matches: 'use workflow', 'use step', @workflow/serde imports, Symbol.for serialization symbols,
 * and WORKFLOW_SERIALIZE/WORKFLOW_DESERIALIZE computed property usage
 */
export const turbopackContentPattern =
  /(use workflow|use step|from\s+(['"])@workflow\/serde\2|Symbol\.for\s*\(\s*(['"])workflow-(?:serialize|deserialize)\3\s*\)|\[\s*WORKFLOW_(?:SERIALIZE|DESERIALIZE)\s*\])/;
